[package]
name = "Dos-Attacker"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full", "sync"] }
rand = "0.8"
futures = "0.3"
